---
# tasks file for awslogs

- name: install awslogs 
  yum: 
    name: awslogs 
    state: present 

- name: copy global configuration 
  copy: 
    src: awslogs.conf 
    dest: /etc/awslogs 
  notify: restart awslogs 

- name: configure awslogs to collect /var/log/messages 
  ini_file: 
    path: /etc/awslogs/config/messages.conf 
    section: /var/log/messages 
    option: "{{ item.option }}" 
    value: "{{ item.value }}"  
  with_items: 
    - { option: file, value: /var/log/messages } 
    - { option: log_group_name, value: /var/log/messages } 
    - { option: log_stream_name, value: "{instance_id}" } 
    - { option: initial_position, value: "start_of_file" } 
    - { option: buffer_duration, value: "5000" } 
    - { option: datetime_format, value: "%Y-%m-%dT%H:%M:%S.%f" }    
  notify: restart awslogs

- name: configure awslogs to collect /var/log/helloworld/helloworld.log 
  ini_file: 
    path: /etc/awslogs/config/helloworld.conf 
    section: /var/log/helloworld/helloworld.log 
    option: "{{ item.option }}" 
    value: "{{ item.value }}"  
  with_items: 
    - { option: file, value: /var/log/helloworld/helloworld.log } 
    - { option: log_group_name, value: /var/log/helloworld/helloworld.log } 
    - { option: log_stream_name, value: "{instance_id}" } 
    - { option: initial_position, value: "start_of_file" } 
    - { option: buffer_duration, value: "5000" } 
    - { option: datetime_format, value: "%Y-%m-%dT%H:%M:%S.%f" }    
  notify: restart awslogs  

- name: start awslogs and enable it 
  service: 
    name: awslogs 
    state: started 
    enabled: yes 
